---
title: "Functional Analysis for Condition"
author: "Isabela Kernin"
date: "January 12, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required packages

```{r}
library(tidyverse)
library(clusterProfiler) # used to run ORA and GSEA
library(org.Hs.eg.db) # mapping of Entrez Ids to all possible GenBank assession numbers
library(ensembldb) # helps use Ensembl-based annotation databases
library(annotables) # contains annotation tables: grch37 contains human annotations based on genome assembly gRCH37 from Ensembl
library(gprofiler2) # ORA similar to clusterProfiler
library(treemap) # used to visualize REVIGO results

load("res_covid_shrunken.Rdata")
```

## ORA

```{r}
## convert to tibble
res_covid2_t <- res_covid2_s %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

## get entrez ids (ensembl) for the gene symbols in DE results
idx <- grch37$symbol %in% rownames(res_covid2_s)
ids <- grch37[idx, ]

## remove duplicate IDs since gene names can map to more than one Ensembl ID since some genes change id over time
non_duplicates <- which(duplicated(ids$symbol) == FALSE)
ids <- ids[non_duplicates, ]

## merge ids with results
res_ids <- inner_join(res_covid2_t, ids, by=c("gene"="symbol"))

## for over-representation analysis need list of background genes(all genes tested for DE) and list of significant genes
all_genes <- as.character(res_ids$ensgene)
sig <- subset(res_ids, (padj<=0.05 & abs(log2FoldChange)>0.58))
sig_genes <- as.character(sig$ensgene)

## run GO enrichment analysis
ego <- enrichGO(gene = sig_genes, 
                universe = all_genes,
                keyType = "ENSEMBL",
                OrgDb = org.Hs.eg.db, 
                ont = "BP", 
                pAdjustMethod = "BH", 
                pvalueCutoff = 0.05, 
                readable = TRUE)

## output results to a table
cluster_summary <- data.frame(ego)
beep(2)
```

```{r}
#dotplot shows number of genes associated with the first n terms
#top n genes by gene ratio = #genes related to GO term/#significant genes
# options for x axis are x = 'GeneRatio' or 'Count'
clusterProfiler::dotplot(ego, showCategory = 20) 

## get condensed categories
gprofiler_results <- gost(query = sig_genes, 
                                  organism = "hsapiens",
                                  ordered_query = F, 
                                  exclude_iea = F, 
                                  user_threshold = 0.05, 
                                  correction_method = "g_SCS",
                                  domain_scope = "custom_annotated",
                                  custom_bg = all_genes)

## Order the results by p-adjusted value
gprofiler_res<- gprofiler_results$result
gprofiler_res <- gprofiler_res[order(gprofiler_res$p_value), ]

## Extract only the 'GO' terms from the results
gprofiler_res_GOs <- gprofiler_res[grep('GO:', gprofiler_res$term_id), ]

## Extract only GO IDs and p-values for downstream analysis
GOpval <- gprofiler_res_GOs[ , c("term_id", "p_value")]
write.table(GOpval, "GOs_covid.txt", quote=FALSE, row.names = FALSE, col.names = FALSE)
```

## GSEA

```{r}
## remove NA values and any Entrez duplicates (due to gene ID conversion)
res_entrez <- subset(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) ==F), ]

## extract fold changes and label
foldchange <- res_entrez$log2FoldChange
names(foldchange) <- res_entrez$entrez

## order fold changes in decreasing order
foldchange <- sort(foldchange, decreasing = T)

## GSEA using gene sets associated with BP Gene Ontology terms
gseaGO <- gseGO(geneList = foldchange, 
              OrgDb = org.Hs.eg.db, 
              ont = 'BP', 
              minGSSize = 20, 
              pvalueCutoff = 0.05,
              verbose = FALSE) 

gseaGO_results <- gseaGO@result

## plot top 20 categories
dotplot(gseaGO, showCategory=20)
beep(2)
```

```{r}
plot_cond <- gseaGO_results[order(gseaGO_results$p.adjust), c("Description", "p.adjust", "NES")]
plot_cond <- plot_cond[1:20, ] #top 20 GO terms by adjusted p-val

ggplot(data = plot_cond, 
       aes(x=reorder(Description, NES), y=NES, fill=p.adjust)) + 
  geom_bar(stat="identity") +
  coord_flip() +
  labs(x="GO Term", y="Normalized Enrichment Score", 
       title="Top 20 GO Terms", 
       subtitle = "Cov+ compared to Cov-") +
  theme(plot.title = element_text(hjust = 0.5),  plot.subtitle = element_text(hjust = 0.5)) +
  scale_fill_distiller(palette="GnBu")
```
