---
title: "Volcano plots"
author: "Isabela Kernin"
date: "January 16, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggrepel)
```


```{r}
## convert results table to tibble
res_shrunken2_t <- res_covid2_s %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 1.5 in either direction
results2_sig_boolean <- res_shrunken2_t %>%
  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 0.58)

##create column to indicate which genes to label
results2_sig_boolean <- results2_sig_boolean %>% 
  arrange(padj) %>% 
  mutate(genelabels = "")

results2_sig_boolean$genelabels[1:20] <- results2_sig_boolean$gene[1:20]

## Volcano plot with named top 20 DE genes
ggplot(results2_sig_boolean, aes(x = log2FoldChange, y = -log10(padj))) +
        geom_point(aes(colour = threshold)) +
        geom_text_repel(aes(label = genelabels)) +
        ggtitle("Top 20 DE Genes for Cov+ compared to Cov-") +
        xlab("log2 fold change") + 
        ylab("-log10 adjusted p-value") +
        theme(legend.position = "none",
              plot.title = element_text(size = rel(1.5), hjust = 0.5),
              axis.title = element_text(size = rel(1.25))) 

```



```{r}
## convert results table to tibble
res_shrunken_t <- res_sex_s %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 1.5 in either direction
results_sig_boolean <- res_shrunken_t %>%
  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 0.58)

##create column to indicate which genes to label
results_sig_boolean <- results_sig_boolean %>% 
  arrange(padj) %>% 
  mutate(genelabels = "")

results_sig_boolean$genelabels[1:20] <- results_sig_boolean$gene[1:20]

## Volcano plot with named top 10 DE genes
ggplot(results_sig_boolean, aes(x = log2FoldChange, y = -log10(padj))) +
        geom_point(aes(colour = threshold)) +
        geom_text_repel(aes(label = genelabels)) +
        ggtitle("Top 20 DE Genes for Male+ compared to Female+") +
        xlab("log2 fold change") + 
        ylab("-log10 adjusted p-value") +
        theme(legend.position = "none",
              plot.title = element_text(size = rel(1.5), hjust = 0.5),
              axis.title = element_text(size = rel(1.25))) 
```


```{r}
## convert results table to tibble
res_shrunken_t <- res_sex_age1s %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 1.5 in either direction
results_sig_boolean <- res_shrunken_t %>%
  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 0.58)

##create column to indicate which genes to label
results_sig_boolean <- results_sig_boolean %>% 
  arrange(padj) %>% 
  mutate(genelabels = "")

results_sig_boolean$genelabels[1:20] <- results_sig_boolean$gene[1:20]

## Volcano plot with named top 10 DE genes
ggplot(results_sig_boolean, aes(x = log2FoldChange, y = -log10(padj))) +
        geom_point(aes(colour = threshold)) +
        geom_text_repel(aes(label = genelabels)) +
        ggtitle("Top 20 DE Genes for Age 0-29 Male+ compared t4o Female+") +
        xlab("log2 fold change") + 
        ylab("-log10 adjusted p-value") +
        theme(legend.position = "none",
              plot.title = element_text(size = rel(1.5), hjust = 0.5),
              axis.title = element_text(size = rel(1.25))) 

```

```{r}
## convert results table to tibble
res_shrunken_t <- res_sex_age2s %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 1.5 in either direction
results_sig_boolean <- res_shrunken_t %>%
  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 0.58)

##create column to indicate which genes to label
results_sig_boolean <- results_sig_boolean %>% 
  arrange(padj) %>% 
  mutate(genelabels = "")

results_sig_boolean$genelabels[1:20] <- results_sig_boolean$gene[1:20]

## Volcano plot with named top 10 DE genes
ggplot(results_sig_boolean, aes(x = log2FoldChange, y = -log10(padj))) +
        geom_point(aes(colour = threshold)) +
        geom_text_repel(aes(label = genelabels)) +
        ggtitle("Top 20 DE Genes for Age 30-69 Male+ compared to Female+") +
        xlab("log2 fold change") + 
        ylab("-log10 adjusted p-value") +
        theme(legend.position = "none",
              plot.title = element_text(size = rel(1.5), hjust = 0.5),
              axis.title = element_text(size = rel(1.25))) 
```

```{r}
## convert results table to tibble
res_shrunken_t <- res_sex_age3s %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 1.5 in either direction
results_sig_boolean <- res_shrunken_t %>%
  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 0.58)

##create column to indicate which genes to label
results_sig_boolean <- results_sig_boolean %>% 
  arrange(padj) %>% 
  mutate(genelabels = "")

results_sig_boolean$genelabels[1:20] <- results_sig_boolean$gene[1:20]

## Volcano plot with named top 10 DE genes
ggplot(results_sig_boolean, aes(x = log2FoldChange, y = -log10(padj))) +
        geom_point(aes(colour = threshold)) +
        geom_text_repel(aes(label = genelabels)) +
        ggtitle("Top 20 DE Genes for Age 69-100 Male+ compared to Female+") +
        xlab("log2 fold change") + 
        ylab("-log10 adjusted p-value") +
        theme(legend.position = "none",
              plot.title = element_text(size = rel(1.5), hjust = 0.5),
              axis.title = element_text(size = rel(1.25))) 

```
